### PR TITLE
don't run ussdService when ussdController isn't

### PR DESCRIPTION
**Pull request by ducaale**
currenty ussd cannot be used normally outside the app when voipUSSD accessability service is enabled. this commit adds a flag that is on when `callUSSDInvoke` is called and is off after `callbackInvoke.over` is called.

### CODE REVIEW

**Comment by romellfudi** [comment]
HI @ducaale , its excellent, but test case throw exception, please run the testCases.

**Comment by romellfudi** [comment]
@ducaale, in test case: update running state before startActivity(dial up). and then be carefully on `callUSSDSendMultipleMessages`.

**Comment by ducaale** [comment]
ok, tests should be fixed now

**Comment by romellfudi** [comment]
great job

**Pull request merged**
