### PR TITLE
Generalize AlertDialog for any manufacturers API

### PR DESCRIPTION
**Pull request by Nivekiba**
In order to avoid list one by one every AlertDialog from each manufacturer API, it should be possible to generalize by searching for the substring "AlertDialog". "PromptDialog" should also be added but for now, the "AlertDialog" class is used by many known manufacturers(Xiaomi, Samsung, oppo, Huawei...)

### CODE REVIEW

**Comment by romellfudi** [comment]
Hi @Nivekiba Why do you add a default "AlertDialog" string? do you have any inconvenience in your phone? 
Please let me know your device specification?

**Comment by Nivekiba** [comment]
Yes for now i used a Xiaomi and the AlertDialog classname has another package not presented in the library. And I'm afraid to change this  classname in the future if my manufacturer or my device specification changes one again

**Comment by romellfudi** [comment]
I'm really sure the Android OS has others AlertDialog, which are not compatible with USSD. Thus I have a list of classes name

**Comment by romellfudi** [comment]
I did this library 4 years ago, I can't remember exactly which cases/flows are

**Comment by Nivekiba** [comment]
I understand your point of view. But the fact is that. in the code, you are checking alertdialog when an accessibilityevent occurs. In this case, there are few AlertDialog which may be concerned by the USSD compatibility.

**Comment by romellfudi** [comment]
Lets do something, refactor the conditions by removing unnecessary conditions in the following files:
ussd-library/src/main/java/com/romellfudi/ussdlibrary/USSDService.java
https://github.com/romellfudi/VoIpUSSD/blob/main/ussd-library-kotlin/src/main/java/com/romellfudi/ussdlibrary/USSDServiceKT.java#L137

To merge the pullrequest

**Comment by Nivekiba** [comment]
I really don't know to code in kotlin

**Comment by romellfudi** [comment]
Hi @Nivekiba do you know pattern design?

Do you know how expose it a function?

My goodness, I wanted add your improvement. Nonetheless, you are junior.

Let me create a branch for you.

**Comment by romellfudi** [comment]
Hello again dear @Nivekiba ,

You can use it the custom library for any of your projects just:
```gradle
	allprojects {ve
		repositories {
			...
			maven { url 'https://jitpack.io' }
		}
	}

	dependencies {
	        implementation 'com.github.romellfudi.VoIpUSSD:kotlin-ussd-library:Nivekiba-workflow-SNAPSHOT'
	}
```

Hope have a great day! 加油！！

**Comment by romellfudi** [comment]
@Nivekiba Please consider donating 💸 to help it improve! or just share the project into any Android Social Group!

**Comment by Nivekiba** [comment]
Hello @romellfudi thanks.
I will do so.
Good day to you too.

**Pull request merged**
