### PR TITLE
in the kotlin library there is no ussd_service_kt

### PR DESCRIPTION
**Pull request by IMoHaMeDHaMdYI**
in the kotlin library there is no ussd_service_kt, it's only ussd_service

### CODE REVIEW

**Comment by romellfudi** [comment]
I see it : https://github.com/romellfudi/VoIpUSSD/tree/master/ussd-library-kotlin/src/main/java/com/romellfudi/ussdlibrary 
Please check again

**Comment by romellfudi** [comment]
I close as you found that class

**Comment by IMoHaMeDHaMdYI** [comment]
I'm talking about the xml file not the kotlin class.

**Comment by IMoHaMeDHaMdYI** [comment]
ussd-library-kotlin/src/main/res/xml/ussd_service.xml

**Comment by romellfudi** [comment]
Hi @IMoHaMeDHaMdYI  When did you fork the repository?, i changed it months ago

**Comment by romellfudi** [comment]
@IMoHaMeDHaMdYI please fork-update all the branches

**Comment by IMoHaMeDHaMdYI** [comment]
couple of days ago,
here is the file https://github.com/romellfudi/VoIpUSSD/tree/master/ussd-library-kotlin/src/main/res/xml

Also by implementing the library version 1.1.k I get the same problem

**Comment by romellfudi** [comment]
@IMoHaMeDHaMdYI other time, say  that error is in the documentation( readme file).

**Pull request merged**
