### PR TITLE
locating correct package in android manifest

### PR DESCRIPTION
**Pull request by nickyrabit**
I have changed the package name in Android manifest so it can locate properly the library . because it was not

### CODE REVIEW

**Comment by romellfudi** [comment]
Thank you for your pull request, but i see you add too many files on one commit, so i cant merge directly, Anyway i change the packagename in manifest: [commit](https://github.com/romellfudi/VoIpUSSD/commit/29837845dfdf83d53f12710aac93e218b3bbcd41)

**Comment by romellfudi** [comment]
Thank you for your pull request, but i see you add too many files on one commit, so i cant merge directly, Anyway i change the packagename in manifest: [commit](https://github.com/romellfudi/VoIpUSSD/commit/29837845dfdf83d53f12710aac93e218b3bbcd41)

**Comment by romellfudi** [comment]
@nickyrabit about .idea files always changes configuration on difference pc/laptops. So i prefer clean with gradle command

**Comment by nickyrabit** [comment]
ok thanks

**Pull request closed without merging**
